---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-male-keti-dev-v1alpha1-malepolicy
  failurePolicy: Fail
  name: vmalepolicy.kb.io
  rules:
  - apiGroups:
    - male.keti.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - malepolicies
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-male-keti-dev-v1alpha1-maleworkload
  failurePolicy: Fail
  name: vmaleworkload.kb.io
  rules:
  - apiGroups:
    - male.keti.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - maleworkloads
  sideEffects: None
