/*
Copyright 2024 KETI.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package controllers

import (
	"context"
	"fmt"
	"time"

	"k8s.io/apimachinery/pkg/api/errors"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	ctrl "sigs.k8s.io/controller-runtime"
	"sigs.k8s.io/controller-runtime/pkg/client"
	"sigs.k8s.io/controller-runtime/pkg/log"

	schedulingv1 "k8s.io/api/scheduling/v1"

	malev1alpha1 "github.com/keti-lab/male-operator/api/v1alpha1"
)

// MalePolicyReconciler reconciles a MalePolicy object
type MalePolicyReconciler struct {
	client.Client
	Scheme *runtime.Scheme
}

//+kubebuilder:rbac:groups=male.keti.dev,resources=malepolicies,verbs=get;list;watch;create;update;patch;delete
//+kubebuilder:rbac:groups=male.keti.dev,resources=malepolicies/status,verbs=get;update;patch
//+kubebuilder:rbac:groups=male.keti.dev,resources=malepolicies/finalizers,verbs=update
//+kubebuilder:rbac:groups=scheduling.k8s.io,resources=priorityclasses,verbs=get;list;watch;create;update;patch;delete

// Reconcile is part of the main kubernetes reconciliation loop
func (r *MalePolicyReconciler) Reconcile(ctx context.Context, req ctrl.Request) (ctrl.Result, error) {
	logger := log.FromContext(ctx)

	policy := &malev1alpha1.MalePolicy{}
	if err := r.Get(ctx, req.NamespacedName, policy); err != nil {
		if errors.IsNotFound(err) {
			return ctrl.Result{}, nil
		}
		return ctrl.Result{}, err
	}

	// Validate weights
	if err := policy.ValidateWeights(); err != nil {
		logger.Error(err, "Invalid weights")
		r.updateCondition(ctx, policy, "Invalid", "WeightsInvalid", err.Error(), metav1.ConditionFalse)
		return ctrl.Result{}, err
	}

	// Validate priority buckets
	if err := policy.ValidatePriorityBuckets(); err != nil {
		logger.Error(err, "Invalid priority buckets")
		r.updateCondition(ctx, policy, "Invalid", "BucketsInvalid", err.Error(), metav1.ConditionFalse)
		return ctrl.Result{}, err
	}

	// Sync PriorityClasses
	if err := r.syncPriorityClasses(ctx, policy); err != nil {
		logger.Error(err, "Failed to sync PriorityClasses")
		r.updateCondition(ctx, policy, "Error", "SyncFailed", err.Error(), metav1.ConditionFalse)
		return ctrl.Result{RequeueAfter: time.Minute}, err
	}

	// Update status
	policy.Status.EffectiveWeights = &policy.Spec.Weights
	policy.Status.LastOverrideSource = "None"
	if err := r.Status().Update(ctx, policy); err != nil {
		logger.Error(err, "Failed to update status")
		return ctrl.Result{}, err
	}

	r.updateCondition(ctx, policy, "Ready", "Synced", "PriorityClasses synced successfully", metav1.ConditionTrue)

	return ctrl.Result{}, nil
}

// syncPriorityClasses creates/updates PriorityClasses based on policy buckets
func (r *MalePolicyReconciler) syncPriorityClasses(ctx context.Context, policy *malev1alpha1.MalePolicy) error {
	for _, bucket := range policy.Spec.PriorityBuckets {
		pc := &schedulingv1.PriorityClass{
			ObjectMeta: metav1.ObjectMeta{
				Name: bucket.Name,
			},
		}

		_, err := ctrl.CreateOrUpdate(ctx, r.Client, pc, func() error {
			pc.Value = bucket.PriorityValue
			pc.GlobalDefault = false
			pc.Description = fmt.Sprintf("Auto-generated by MALE operator for score range [%.2f, %.2f]",
				bucket.Min, bucket.Max)

			// Set owner reference
			if err := ctrl.SetControllerReference(policy, pc, r.Scheme); err != nil {
				return err
			}

			return nil
		})

		if err != nil {
			return fmt.Errorf("failed to create/update PriorityClass %s: %w", bucket.Name, err)
		}

		logger := log.FromContext(ctx)
		logger.Info("PriorityClass synced", "name", bucket.Name)
	}

	return nil
}

func (r *MalePolicyReconciler) updateCondition(ctx context.Context, policy *malev1alpha1.MalePolicy,
	conditionType, reason, message string, status metav1.ConditionStatus) {
	condition := metav1.Condition{
		Type:               conditionType,
		Status:             status,
		Reason:             reason,
		Message:            message,
		LastTransitionTime: metav1.Now(),
	}

	// Update or add condition
	existing := false
	for i := range policy.Status.Conditions {
		if policy.Status.Conditions[i].Type == conditionType {
			policy.Status.Conditions[i] = condition
			existing = true
			break
		}
	}
	if !existing {
		policy.Status.Conditions = append(policy.Status.Conditions, condition)
	}

	if err := r.Status().Update(ctx, policy); err != nil {
		logger := log.FromContext(ctx)
		logger.Error(err, "Failed to update condition", "type", conditionType)
	}
}

// SetupWithManager sets up the controller with the Manager.
func (r *MalePolicyReconciler) SetupWithManager(mgr ctrl.Manager) error {
	return ctrl.NewControllerManagedBy(mgr).
		For(&malev1alpha1.MalePolicy{}).
		Complete(r)
}
